global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ml-inference'
    static_configs:
      - targets: ['ml-inference:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'data-ingestion'
    static_configs:
      - targets: ['data-ingestion:8002']
    metrics_path: '/metrics'
    scrape_interval: 10s
EOF
